# config/services.yaml

services:
    App\Security\ApiKeyAuthenticator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $tokenStorage: '@security.token_storage'
            $httpUtils: '@security.http_utils'
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    App\Security\ApiKeyUserProvider:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
